name: Glade Web Build & Deploy
on:
  push:
    branches:
      - main
      - webgl-action
jobs:
  build-deploy:
    name: Web Deploy 🚀
    runs-on: self-hosted
    strategy:
      fail-fast: true
      matrix:
        targetPlatform:
          - WebGL
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Prepare Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: auto
      - name: Setup S3cmd to handle artifact upload
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: linode
          region: 'us-southeast-1'
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}
      - name: Upload build artifcats using S3cmd
        run: |
          s3cmd --no-mime-magic --acl-public --delete-removed --delete-after sync build/WebGL/ s3://omni-bucket
          s3cmd modify --add-header="Content-Encoding: gzip" 's3://omni-bucket/Build/*.gz'
          s3cmd ws-info s3://omni-bucket
